# Generated by Django 2.2.16 on 2023-02-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20230127_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(help_text='Группа, к которой относится пост', max_length=200, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Введите текст постов', verbose_name='Содержание'),
        ),
    ]
