# Generated by Django 2.2.16 on 2023-03-02 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20230302_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appraise',
            old_name='author',
            new_name='post',
        ),
    ]
