# Generated by Django 2.2.16 on 2023-03-02 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20230302_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraise',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraising', to='posts.Post'),
        ),
    ]
